name: Deploy Node.js App to Apache Tomcat
'on':
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    # fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      # - name: Log into Docker Hub
      - name: Log into Docker Hub
        run : echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Node.js App
        run: |
          npm install
          npm run build
      - name: Build Docker Image
        run: docker build -t node-app:latest .
      - name: Push Docker Image to Docker Hub
        run: 'docker push manilmunjal/node-app:latest'
      - name: Run Docker Container
        run: 'docker run -d -p 8080:8080 manilmunjal/node-app:latest'
